### ISSUE TITLE
Milestone 1 Tracker - Hello World Triangle

### ISSUE THREAD

**Issue by IsaacMarovitz** [IsaacMarovitz/SharpMetal#2]
- [x] All enums, structs, classes, and functions have some form of implementation
- [x] Various API improvements
    - `new MTLDevice(MTLDevice.MTLCreateSystemDefaultDevice());` -> `MTLDevice.CreateSystemDefaultDevice();`
- [x] Fix MTLSize crash
- [x] Remove unnecessary Get...() methods that are covered by property getters
- [x] Fix inheritance
- [x] Build up other foundational boilerplate to get a window open to render in
- [x] Fix NSError-centric APIs
- [x] Easy NSString <-> String interop (sorta, room for improvement)
- [ ] Fix some mismatched method selectors
- [ ] Fix memory fire hose
- [ ] Delegates
- [ ] Easy NSArray indexing

**Comment by IsaacMarovitz** [comment]
<img width="1552" alt="Screenshot 2023-07-25 at 07 30 41" src="https://github.com/IsaacMarovitz/SharpMetal/assets/42140194/b5633244-5910-499e-adfd-efd7740ca2b5">

The first major milestone has been hit. Clear color is rendering.

**Comment by IsaacMarovitz** [comment]
<img width="624" alt="Screenshot 2023-07-25 at 13 43 40" src="https://github.com/IsaacMarovitz/SharpMetal/assets/42140194/0dbd45b5-e5bc-429e-ac34-4da007dae815">

Hello World Triangle achieved!
